travis:
  secure:
    BINSTAR_TOKEN: napDazqHaS6wTNvRnf5vD5P+TkT4kAGdiH2qw9i0RNLng7iz9lyq3WjBFAWC8hKgJgXYeJy+3aY6IQ/ZQKrzbViPpOnExJssI0Q40QTcJI0YsJtRVrybyc2eXssOsquObpsBeBlEF4PSRcf0hBrbaH/gUhLJjPdK69p892m0hDdvUfo3chRFrQrcvklW/QEQoHAWstXvqDP6bVCq2cM+YwTz6KaA15c+NsBRIQPVgoXxb7Ve+A37pL9ve3mtwlzxf/14aQrHCWR2BZ+TmlraJXOiscz4wsWKgpCAyjUgo2EZKOW7r6Bm+RNhApUrlt6udGmJLGGqyB9QMFImweFl4AebZASkasuVFdEFJta0JJ9nqowEUH+JeMvNa7d+oFXa83YTAC7iByxGx59PEPrhpuE1tpo2xW143+qDbhY24s4AYNFE2ZN8TxMFQYottnzN1RPPJULFNIvfIol2M5j/iKbVV7SVhZ5swQJ+X8d+cSPQyirArNQFajuMm+O/nudg8c9NbGLH1mSiIeZdZvR4bmpu/9R7CCoUe0mEsw63J+wQcIxBaDoNDqUH6Xo3XNhwXNQ+BMTueGqwpe6t0MPO6W1Yec5BOUZyk4G35dFN+mAC3X8f5cxsbrmEuxB/bHJEGEBF/IIjVfwXkO9HtUzILxzq3dOt2ouwY14IYO+Nphg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
